# Generated by Django 5.1.3 on 2024-12-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0468_alter_facilitypatientstatshistory_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyround',
            name='deprecated_covid_category',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='contact_with_confirmed_carrier',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='contact_with_suspected_carrier',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='covin_id',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='date_declared_positive',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='estimated_contact_date',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='has_SARI',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='is_declared_positive',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='is_vaccinated',
        ),
        migrations.RemoveField(
            model_name='historicalpatientregistration',
            name='last_vaccinated_date',
        ),
        migrations.RemoveField(
            model_name='patientconsultation',
            name='deprecated_covid_category',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='contact_with_confirmed_carrier',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='contact_with_suspected_carrier',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='covin_id',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='date_declared_positive',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='estimated_contact_date',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='has_SARI',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='is_declared_positive',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='is_vaccinated',
        ),
        migrations.RemoveField(
            model_name='patientregistration',
            name='last_vaccinated_date',
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.IntegerField(choices=[(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (9, 'Govt Labs'), (10, 'Private Labs'), (800, 'Primary Health Centres'), (802, 'Family Health Centres'), (803, 'Community Health Centres'), (830, 'Taluk Hospitals'), (840, 'Women and Child Health Centres'), (860, 'District Hospitals'), (870, 'Govt Medical College Hospitals'), (900, 'Co-operative hospitals'), (910, 'Autonomous healthcare facility'), (1100, 'First Line Treatment Centre'), (1200, 'Second Line Treatment Center'), (1300, 'Shifting Centre'), (1500, 'Request Approving Center'), (1510, 'Request Fulfilment Center'), (1600, 'District War Room')]),
        ),
        migrations.AlterField(
            model_name='historicalpatientregistration',
            name='source',
            field=models.IntegerField(choices=[(10, 'CARE'), (30, 'STAY')], default=10),
        ),
        migrations.AlterField(
            model_name='patientcontactdetails',
            name='mode_of_contact',
            field=models.IntegerField(choices=[(1, 'TOUCHED_BODY_FLUIDS'), (2, 'DIRECT_PHYSICAL_CONTACT'), (3, 'CLEANED_USED_ITEMS'), (4, 'LIVE_IN_SAME_HOUSEHOLD'), (5, 'CLOSE_CONTACT_WITHOUT_PRECAUTION'), (7, 'HEALTH_CARE_WITH_PPE'), (8, 'SHARED_SAME_SPACE_WITHOUT_HIGH_EXPOSURE'), (9, 'TRAVELLED_TOGETHER_WITHOUT_HIGH_EXPOSURE')]),
        ),
        migrations.AlterField(
            model_name='patientregistration',
            name='source',
            field=models.IntegerField(choices=[(10, 'CARE'), (30, 'STAY')], default=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.IntegerField(choices=[(0, 'Total'), (2, 'Hostel'), (3, 'Single Room with Attached Bathroom'), (40, 'KASP Beds'), (50, 'KASP ICU beds'), (60, 'KASP Oxygen beds'), (70, 'KASP Ventilator beds'), (1, 'General Bed'), (10, 'ICU'), (20, 'Ventilator'), (150, 'Oxygen beds')]),
        ),
        migrations.AlterField(
            model_name='shiftingrequest',
            name='assigned_facility_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Educational Inst'), (2, 'Private Hospital'), (3, 'Other'), (4, 'Hostel'), (5, 'Hotel'), (6, 'Lodge'), (7, 'TeleMedicine'), (9, 'Govt Labs'), (10, 'Private Labs'), (800, 'Primary Health Centres'), (802, 'Family Health Centres'), (803, 'Community Health Centres'), (830, 'Taluk Hospitals'), (840, 'Women and Child Health Centres'), (860, 'District Hospitals'), (870, 'Govt Medical College Hospitals'), (900, 'Co-operative hospitals'), (910, 'Autonomous healthcare facility'), (1100, 'First Line Treatment Centre'), (1200, 'Second Line Treatment Center'), (1300, 'Shifting Centre'), (1500, 'Request Approving Center'), (1510, 'Request Fulfilment Center'), (1600, 'District War Room')], default=None, null=True),
        ),
    ]
